package de.mehtrick.jvior.generator;

import org.junit.Test;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class JviorGeneratorTest {
	@Test
	public void testSomeLibraryMethod() {
	}

}
