package de.mehtrick.jvior.generator;

import static org.junit.Assert.assertEquals;

import de.mehtrick.jvior.sample.AbstractTestFoo;
import de.mehtrick.jvior.sample.Bar;
import de.mehtrick.jvior.sample.Foo;
import lombok.Data;
import lombok.EqualsAndHashCode;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

@Data
@EqualsAndHashCode(callSuper = false)
public class TestFoo extends AbstractTestFoo {

	private Bar bar;
	private Foo foo;
	private String messageOfFoo;

	@Override
	public void when_FooWantsToDrinkBottleOfBeer(String param1) {
		messageOfFoo = foo.drinkBeerOfBar(bar.getBottlesOfBeer());
	}

	@Override
	public void given_ABar() {
		setBar(new Bar());
	}

	@Override
	public void given_ThereAreBottlesOfBeer(String param1) {
		bar.setBottlesOfBeer(Integer.valueOf(param1));
	}

	@Override
	public void given_AFoo() {
		setFoo(new Foo());
	}

	@Override
	public void given_ThereAreBottlesOfWine(String param1) {
		bar.setBottlesOfWine(Integer.valueOf(param1));

	}

	@Override
	public void then_FooSays(String param1) {
		assertEquals(param1, messageOfFoo);

	}

}
