package de.mehtrick.jvior.generator;

import java.io.FileNotFoundException;

import org.junit.Test;

import de.mehtrick.jvior.base.JviorMissingPropertyException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class JviorGeneratorTest {
	@Test
	public void testSomeLibraryMethod() throws JviorMissingPropertyException, FileNotFoundException {
		JviorCodeGeneratorApplication.main(new String[] { "path=src/test/resources/jvior.yaml", "folder=src/test/resources/",
				"package=de.mehtrick.jvior", "gendir=src/gen/java",
				"extendedTestclass=de.mehtrick.jvior.AbstractTestclass" });
	}
	
	@Test
	public void testMissingParameter() throws JviorMissingPropertyException, FileNotFoundException {
		JviorCodeGeneratorApplication.main(new String[] { "path=src/test/resources/jvior.yaml", "folder=src/test/resources/",
				"package=de.mehtrick.jvior", "gendir=src/gen/java",
				"extendedTestclass=de.mehtrick.jvior.AbstractTestclass" });
	}

}
