package de.mehtrick.bjoern.generator;

import java.io.FileNotFoundException;
import java.io.IOException;

import org.junit.Test;

import de.mehtrick.bjoern.base.BjoernMissingPropertyException;
import de.mehtrick.bjoern.generator.BjoernCodeGeneratorApplication;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class BjoernGeneratorTest {
	@Test
	public void testSomeLibraryMethod() throws BjoernMissingPropertyException, IOException {
		BjoernCodeGeneratorApplication.main(new String[] { "path=src/test/resources/specification/bjoern.yaml",
				"folder=src/test/resources/", "package=de.mehtrick.bjoern", "gendir=src/gen/java",
				"extendedTestclass=de.mehtrick.bjoern.AbstractTestclass" });
	}

	@Test
	public void testMissingParameter() throws BjoernMissingPropertyException, IOException {
		BjoernCodeGeneratorApplication.main(new String[] { "path=src/test/resources/bjoern.yaml",
				"folder=src/test/resources/", "package=de.mehtrick.bjoern", "gendir=src/gen/java",
				"extendedTestclass=de.mehtrick.bjoern.AbstractTestclass" });
	}

}
