
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import de.mehtrick.jvior.parser.modell.yaml.JviorYMLModell;
import de.mehtrick.jvior.parser.reader.JviorYMLReader;

public class JviorParserTest {

	@Test
	public void testSomeLibraryMethod() {
		JviorYMLModell readSpec = new JviorYMLReader().readSpec(null);
		System.out.println(readSpec);
	}
}
