package de.mehtrick.jvior;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.Assert.fail;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import de.mehtrick.jvior.parser.JviorParser;
import de.mehtrick.jvior.parser.modell.BDDKeyword;
import de.mehtrick.jvior.parser.modell.Jvior;
import de.mehtrick.jvior.parser.modell.JviorStatement;
import de.mehtrick.jvior.parser.reader.JviorFileExtensionInvalidException;
import de.mehtrick.jvior.parser.reader.JviorYMLReaderException;

public class JviorParserTest {

	@Test
	public void testJviorFullWithoutErrors() {
		String path = "src/test/resources/jvior.yaml";
		Jvior jvior = JviorParser.parseSpec(path);
		assertThat(jvior.getFilePath()).isEqualTo(path);
		assertThat(jvior.getFeature()).isEqualTo("Test eines Getraenkeautomaten");
		assertThat(jvior.getScenarios()).hasSize(2);
	}

	@Test
	public void testWrongFileExctension() {
		try {
			JviorParser.parseSpec("src/test/resources/jvior.text");
			fail("Exception should have been thrown");
		} catch (JviorFileExtensionInvalidException e) {
			assertThat(e.getMessage()).contains(JviorFileExtensionInvalidException.MESSAGE);
		}
	}

	@Test
	public void testFileNotFound() {
		String path = "src/test/resources/notFound.yml";
		try {
			JviorParser.parseSpec(path);
			fail("Exception should have been thrown");
		} catch (JviorYMLReaderException e) {
			assertThat(e.getMessage()).contains("No file found under the path " + path);
		}
	}

	@Test
	public void testJviorStatementBuilder() {
		String string = "Hallo wie \"geht es dir\" du \"1\" stricher";
		JviorStatement statement = new JviorStatement(string, BDDKeyword.GIVEN);
		assertThat(statement.getPrimitiveStatement()).isEqualTo(string);
		assertThat(statement.getStatementWithoutParameters()).isEqualTo("given_HalloWieDuStricher");
		assertThat(statement.getParameters()).hasSize(2).contains("geht es dir", "1");
	}

}
