package de.mehtrick.jvior;

import static org.assertj.core.api.Assertions.assertThat;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import de.mehtrick.jvior.parser.JviorParser;
import de.mehtrick.jvior.parser.modell.BDDKeyword;
import de.mehtrick.jvior.parser.modell.JviorStatement;

public class JviorParserTest {

	@Test
	public void testJviorFullWithoutErrors() {
		new JviorParser().parseSpec("src/test/resources/JnarioBasisFeature.yml");
	}

	@Test
	public void testJviorStatementBuilder() {
		String string = "Hallo wie \"geht es dir\" du \"1\" stricher";
		JviorStatement statement = new JviorStatement(string, BDDKeyword.GIVEN);
		assertThat(statement.getPrimitiveStatement()).isEqualTo(string);
		assertThat(statement.getStatementWithoutParameters()).isEqualTo("given_HalloWieDuStricher");
		assertThat(statement.getParameters()).hasSize(2).contains("geht es dir", "1");
	}

}
